### ISSUE TITLE
Looping on Save

### ISSUE THREAD

**Issue by ThePoundSign** [Lonefy/vscode-JS-CSS-HTML-formatter#20]
After installing JS-CSS-HTML-formatter, when I try to save any JSON file on a mac, it keeps looping and blocks IDE from responding.

Here is the Video Link for the issue: http://www.screencast.com/t/MH4yLw7p

**Comment by agkphysics** [comment]
I am having a similar problem on Linux. It occurs with both HTML and JSON and seems to have something to do with the last line of the file being a single newline.

Setting the config option `"end_with_newline": true` for JS, CSS and HTML seems to solve the problem for me, or you can set `"onSave": false` in order to only manually format each file.

**Comment by dreed47** [comment]
same problem for me...on a Mac
